config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  devise_for :users, controllers: {
    invitations: 'users/invitations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  get '/support', to: 'pages#support'
  get '/app', to: 'pages#app'
  get 'privacy', to: 'pages#privacy'

  get '/connexion', to: 'pages#connexion'
  get '/mot-de-passe-oublie', to: 'pages#forgot_password'

  resources :logos, only: :show
  resources :avatars, only: :show

  namespace :api, defaults: { format: 'json' } do
    get 'current_user', to: 'current_user#show'
    get 'switch/:id', to: 'current_user#switch', as: :switch_user
    get 'switch_back', to: 'current_user#switch_back', as: :switch_back
    post 'connect_with_google', to: 'sessions#connect_with_google', as: :connect_with_google
    post 'login', to: 'sessions#login', as: :login

    get '/:model/config', to: 'config#show'

    resources :users
    patch '/users/:id/enable', to: 'users#enable'
    patch '/users/:id/disable', to: 'users#disable'
    patch '/users/:id/add_role', to: 'users#add_role'
    patch '/users/:id/remove_role', to: 'users#remove_role'
    post '/users/:id/send_invitation', to: 'users#send_invitation'

    resources :churches
    post '/churches/:id/members', to: 'churches#add_members'
    delete '/churches/:id/members/:membership_id', to: 'churches#remove_members'
    post '/churches/:id/roles/edit', to: 'churches#edit_roles'

    resources :regions
    post '/regions/:id/members', to: 'regions#add_members'
    post '/regions/:id/roles/edit', to: 'regions#edit_roles'

    resources :associations
    post '/associations/:id/members', to: 'associations#add_members'
    post '/associations/:id/roles/edit', to: 'associations#edit_roles'

    resources :fees

    get '/notifications', to: 'notifications#index'
    patch '/notifications/:id/mark_as_read', to: 'notifications#mark_as_read'
    patch '/notifications/mark_all_as_read', to: 'notifications#mark_all_as_read'

    resources :device_tokens, only: [:create, :destroy]

    get '/profile', to: 'profile#show'

    get '/search', to: 'search#index'

    namespace :me do
      resources :events, only: [:index]
    end

    resources :memberships, only: [:update, :destroy]

    resources :campaigns
    patch '/campaigns/:id/change_state', to: 'campaigns#change_state'
    get '/campaigns/:id/voters_count', to: 'campaigns#voters_count'
    resources :events
    resources :posts
    resources :votes, only: [:index, :show, :create]
    resources :feed, only: [:index]

    resources :roles

    resources :files, only: [:destroy]
    resources :documents
    post '/update_order_documents', to: 'documents#update_order'
    resources :categories

    resources :push_notifications, only: [:index, :create, :update, :destroy]
    post '/push_notifications/send', to: 'push_notifications#send_notification'

    get 'referentiels/:referentiel', to: 'referentiels#show'
    get 'menus/:menu', to: 'menus#show'
  end

  # ADMIN SUBDOMAIN
  namespace :admin do
    resources :users, only: :index
    resources :churches, only: :index
    resources :associations, only: :index
    resources :campaigns, only: :index
    resources :events, only: :index
    resources :posts, only: :index
    resources :roles, only: :index
    resources :fees, only: :index
    resources :documents, only: :index
    resources :push_notifications, only: :index
    resources :regions, only: :index
    
    root to: redirect('/admin/users'), as: :root
  end

  # ASSOCIATION SUBDOMAIN
  namespace :association do
    resources :associations, only: :index
    resources :campaigns, only: :index

    root to: redirect('/association/associations'), as: :root
  end

  # REGION
  namespace :region do
    resources :members, only: :index
    resources :campaigns, only: :index
    resources :events, only: :index
    resources :posts, only: :index

    root to: redirect('/region/members'), as: :root
  end

  # ME SUBDOMAIN
  namespace :me, path: '' do
    get '/feed', to: 'feed#show', as: :feed
    get '/annuaire', to: 'annuaire#show', as: :annuaire
    get '/mon-profil', to: 'profile#show', as: :me
    get '/documents', to: 'documents#index', as: :documents
    get '/campaigns', to: 'campaigns#index', as: :votes
    get '/actus/:post', to: 'posts#show', as: :post
    get '/evenements/:event', to: 'events#show', as: :event

    root to: redirect('/feed'), as: :root
  end

  get '/campaigns/:id', to: 'campaigns#show'

  root to: redirect('/connexion')
end

app/controllers/admin/campaigns_controller.rb
class Admin::CampaignsController < AdminController
  def index
  end
end

app/controllers/api/campaigns_controller.rb
class Api::CampaignsController < ApiController
  before_action :set_campaign, only: [:show, :update, :destroy, :change_state, :voters_count]

  def index
    domain = params[:domain] || 'me'
    campaigns = []

    case domain
    when 'admin'
      campaigns = Campaign
                    .joins(:structure)
                    .select('campaigns.*, structures.name AS structure_name')
                    .order(id: :desc)
    when 'association'
      campaigns = campaigns_for(current_user.associations_responsabilities)
    when 'region'
      campaigns = campaigns_for(current_user.regions_responsabilities)
    end

    render json: { campaigns: campaigns }
  end

  def show
    motions         = @campaign.motions.order(id: :asc)
    voting_tables   = @campaign.voting_tables
    results         = @campaign.results
    choices_results = @campaign.choices_results
    free_results    = @campaign.free_results
    voters          = @campaign.voters
    render json: {
      campaign:        @campaign,
      motions:         motions,
      voting_tables:   voting_tables,
      results:         results,
      free_results:    free_results,
      choices_results: choices_results,
      voters:          voters
    }
  end

  def create
    campaign = Campaign.new(campaign_params)
    if campaign.save
      save_motions(campaign, params[:campaign][:motions])
      save_voting_tables(campaign, params[:campaign][:voting_tables])
      render json: { status: 200, campaign: campaign }
    else
      render json: { status: 422, errors: campaign.errors }
    end
  end

  def update
    if @campaign.update(campaign_params)
      save_motions(@campaign, params[:campaign][:motions])
      save_voting_tables(@campaign, params[:campaign][:voting_tables])
      render json: { status: 200, campaign: @campaign }
    else
      render json: { status: 422, errors: @campaign.errors }
    end
  end

  def destroy
    @campaign.destroy
    render json: { status: 200 }
  end

  def change_state
    if @campaign.fire_state_event(params[:state_event])
      render json: { status: 200, campaign: @campaign }
    else
      render json: { status: 422, errors: @campaign.errors }
    end
  end

  def voters_count

    voters_count = @campaign.voters.count
    render json: { voters_count: voters_count }
  end

  private

  def save_motions(campaign, motions_params)
    motion_ids = motions_params.map { |motion| motion[:id] }
    Motion.where(campaign_id: campaign.id).where.not(id: motion_ids).delete_all
    motions_params.each do |motion_params|
      motion = campaign.motions.find_by(id: motion_params[:id])

      if motion.nil?
        campaign.motions.build(
          name:    motion_params[:name],
          kind:    motion_params[:kind],
          order:   motion_params[:order],
          choices: motion_params[:choices],
          max_choice: motion_params[:max_choice]
        )
      else
        motion.update(
          name:    motion_params[:name],
          kind:    motion_params[:kind],
          order:   motion_params[:order],
          choices: motion_params[:choices],
          max_choice: motion_params[:max_choice]
        )
      end
    end

    campaign.save
  end

  def save_voting_tables(campaign, voting_tables_params)
    voting_table_ids = voting_tables_params.map { |voting_table| voting_table[:id] }
    VotingTable.where(campaign_id: campaign.id).where.not(id: voting_table_ids).delete_all
    voting_tables_params.each do |voting_table_params|
      voting_table = campaign.voting_tables.find_by(id: voting_table_params[:id])

      if voting_table.nil?
        campaign.voting_tables.build(
          position:  voting_table_params[:position],
          as_member: voting_table_params[:as_member],
          voting:    voting_table_params[:voting],
        )
      else
        voting_table.update(
          position:  voting_table_params[:position],
          as_member: voting_table_params[:as_member],
          voting:    voting_table_params[:voting],
        )
      end
    end

    campaign.save
  end

  def set_campaign
    @campaign = Campaign.find(params[:id])
  end

  def campaign_params
    params[:campaign].permit(:name, :structure_id)
  end

  def campaigns_for(responsabilities)
    structure_ids = responsabilities.pluck(:id)
    return [] if structure_ids.empty?

    Campaign.joins(:structure)
            .select('campaigns.*, structures.name AS structure_name')
            .where(structure_id: structure_ids).order(id: :desc)
  end

end

app/controllers/association/campaigns_controller.rb
class Association::CampaignsController < AssociationController
  def index
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def show
    @campaign = Campaign.find params[:id]

    respond_to do |format|
      format.pdf do
        render pdf: "#{@campaign.name} - resultats", layout: "layouts/pdf"
      end
    end
  end
end

app/controllers/me/campaigns_controller.rb
class Me::CampaignsController < MeController
  def index
  end
end

app/controllers/region/campaigns_controller.rb
class Region::CampaignsController < RegionController
  def index
  end
end

app/views/campaigns/index.html.haml
.breadcrumbs
  .page-header
    %h1 Mes votes

.content.mt-3
  .container-fluid
    .card
      .card-header
        %strong Liste des bulletins de votes

      .card-body
        .alert.alert-info
          Voici la liste des campagne de votes pour lesquelles vous ou vos églises sont membres.


        .table-responsive
          %table.table.table-striped.table-sm
            %thead
              %tr
                %th Structure concernée
                %th Bulletin
                %th

            - @campaigns.each do |campaign|
              %tr
                %td= campaign.structure_name
                %td= campaign.name
                %td
                  - if campaign.opened?
                    = link_to campaign_path(campaign.id), class: 'btn btn-sm btn-primary' do
                      Commencer le vote
                      = icon 'fa', 'arrow-right'
                  - else
                    .badge.badge-warning
                      Les votes ne sont pas encore ouverts

app/views/campaigns/show.html.haml
.breadcrumbs
  .page-header
    %h1 Mes votes

.content.mt-3
  .container-fluid
    .card
      .card-header
        .float-left
          = @campaign.structure_name
        .card-actions.float-right
          = link_to :campaigns, class: 'btn btn-default' do
            = icon 'fa', "angle-left"
            Revenir aux campagnes

      .card-body
        = form_for :votings, url: voting_path do |f|
          = f.hidden_field :campaign_id, value: @campaign.id
          .row
            .col-md-6
              %h2.h5.mb-3
                Bulletin de vote

              - if @user.has_voted?(@campaign) && @presidences.blank?
                %p.text-danger Vous avez déjà rempli tous vos bulletins
              - else
                .well.bg-light.p-3
                  %h3.h5.text-center.mb-3= @campaign.name
                  %table.table
                    - @campaign.motions.each do |motion|
                      %tr
                        %th
                          = motion.name
                        %td
                          = hidden_field_tag "vote[#{motion.id}][motion_id]", motion.id
                          = get_field "vote[#{motion.id}][result]", motion.kind

            .col-md-6
              .alert.alert-info
                %p
                  Il est possible que vous ayez plusieurs bulletins de vote disponibles (en fonction du nombre de présidence et du niveau de reconnaissance).

                %p
                  Chaque ligne, ci-dessous, vous indique en quelle qualité vous votez.

                %p
                  Votre vote peut être différent pour chaque qualité. Pour cela, il suffit de

                %ul.pl-3
                  %li Remplir le bulletin une première fois
                  %li Selectionner la qualité qui correspond
                  %li Valider le vote
                  %li Recommencer autant de fois que nécessaire.


              %h2.h4.mb-3 Mes bulletins en qualité de Président d'église ou d'oeuvre :

              - @presidences.each_with_index do |s, index|

                - if @structure.is_member?(s)
                  - if @structure.member_can_vote?(s) && !@campaign.has_already_vote?(s)
                    // MEMBRE DE L'ASSOC, CAN_VOTE
                    = render 'votings', voter: s, as_member: true

                  - elsif !@structure.member_can_vote?(s)
                    // MEMBRE DE L'ASSOC, MAIS CANT_VOTE
                    .alert.alert-danger
                      %b= "Présidence de <b>#{s.name}</b> (#{s.town})".html_safe
                      %br
                      = @structure.member_cant_vote_note_friendly(s)

                - elsif @campaign.structure_can_vote?(s, false) && !@campaign.has_already_vote?(s)
                  // NON MEMBRE, CAN VOTE
                  = render 'votings', voter: s, as_member: false



              %h2.h4.mb-3 Mon bulletin en qualité de personne physique :

              - if @structure.is_member?(@user)
                - if @campaign.user_can_vote?(@user) && !@campaign.has_already_vote?(@user)
                  // MEMBRE DE L'ASSOC, CAN_VOTE
                  = render 'votings', voter: @user, as_member: true

                - elsif !@structure.member_can_vote?(@user)
                  // MEMBRE DE L'ASSOC, MAIS CANT_VOTE
                  .alert.alert-danger
                    = @structure.member_cant_vote_note_friendly(@user)

              - elsif @campaign.user_can_vote?(@user, false) && !@campaign.has_already_vote?(@user)
                // NON MEMBRE, CAN VOTE
                = render 'votings', voter: @user, as_member: false


          - unless @campaign.can_vote?
            .alert.alert-danger.mt-3 Les votes n'ont pas encore commencés
          - else
            - if !@user.has_voted?(@campaign) || !@presidences.blank?
              .row
                .col-md-12
                  .text-center.mt-3
                    %button.btn.btn-success.submit-vote{type: :submit}
                      = icon 'fa', 'warning'
                      JE VALIDE MON VOTE
                      = icon 'fa', 'warning'

app/views/campaigns/show.pdf.haml
%h2.font-weight-bold
  = @campaign.structure_name

%h2
  Nom de la campagne :
  = @campaign.name

- unless @campaign.motions.where(kind: [:binary, :neutral, :free]).blank?
  %table{border: 1, width: '100%', style: 'margin-bottom: 20px'}
    - unless @campaign.motions.where(kind: [:binary, :neutral]).blank?
      %tr
        %th{rowspan: 2}
        %th{rowspan: 2} Nb de votants
        %th{colspan: 3} Voix exprimés
        %th{rowspan: 2, colspan: 2}
          Voix non exprimés
          %br
          (Blanc ou neutre)

        - if @campaign.has_consultative_votes?
          %th{rowspan: 2} Nb de votants
          %th{colspan: 3} Voix exprimés
          %th{rowspan: 2, colspan: 2}
            Voix non exprimés
            %br
            (Blanc ou neutre)

      %tr
        %th Oui
        %th Non
        %th Total

        - if @campaign.has_consultative_votes?
          %th Oui
          %th Non
          %th Total

      - @campaign.motions.where(kind: [:neutral, :binary]).each do |motion|
        - oui_count = motion.votes.officials.where(result: "oui").count
        - non_count = motion.votes.officials.where(result: "non").count
        - neutral_count = motion.votes.officials.where(result: ["neutre", nil]).count

        %tr
          %td= motion.name
          %td= motion.votes.officials.count
          %td
            = oui_count
            %small= "(#{number_to_percentage (oui_count.to_f/(oui_count+non_count).to_f)*100, precision: 2})"
          %td
            = non_count
            %small= "(#{number_to_percentage (non_count.to_f/(oui_count+non_count).to_f)*100, precision: 2})"
          %td= non_count + oui_count

          %td{colspan: 2}= neutral_count


          - if @campaign.has_consultative_votes?
            - oui_count = motion.votes.consultatives.where(result: "oui").count
            - non_count = motion.votes.consultatives.where(result: "non").count
            - neutral_count = motion.votes.consultatives.where(result: ["neutre", nil]).count

            %td= motion.votes.consultatives.count
            %td
              = oui_count
              %small= "(#{number_to_percentage (oui_count.to_f/(oui_count+non_count).to_f)*100, precision: 2})"
            %td
              = non_count
              %small= "(#{number_to_percentage (non_count.to_f/(oui_count+non_count).to_f)*100, precision: 2})"

            %td= non_count + oui_count

            %td= neutral_count

    - unless @campaign.motions.where(kind: :free).blank?
      %tr
        %th
        %th{colspan: 3} Répartition des propositions
        %th Votants
        %th Exprimés
        %th Blancs
      - @campaign.motions.where(kind: :free).each do |motion|
        %tr
          %td= motion.name
          %td{colspan: 3}
            %ul.list-unstyled
              - motion.votes.officials.select(:result, 'COUNT(*) as count').group(:result).each do |r|
                %li.list-unstyled-item= "#{r.result} (#{r.count})"
          %td= motion.votes.officials.count
          %td= motion.votes.officials.where("result IS NOT NULL").count
          %td= motion.votes.officials.where(result: nil).count

          - if @campaign.has_consultative_votes?
            %td{colspan: 3}
              %ul.list-unstyled
                - motion.votes.consultatives.select(:result, 'COUNT(*) as count').group(:result).each do |r|
                  %li.list-unstyled-item= "#{r.result} (#{r.count})"
            %td= motion.votes.consultatives.count
            %td= motion.votes.consultatives.where("result IS NOT NULL").count
            %td= motion.votes.consultatives.where(result: nil).count

- unless @campaign.motions.where(kind: :choices).blank?
  - @campaign.motions.where(kind: :choices).each do |motion|
    %table{border: 1, width: '100%', style: 'margin-bottom: 20px'}
      %tr
        %th{colspan: (motion.choices.split(',').count + 3)*2 }= motion.name
      %tr
        - motion.choices.split(',').each do |choice|
          %th= choice
        %th Votants
        %th Exprimés
        %th Blancs
        - motion.choices.split(',').each do |choice|
          %th= choice
        %th Votants
        %th Exprimés
        %th Blancs

      %tr
        - motion.choices.split(',').each do |choice|
          %td
            = motion.votes.officials.where(result: choice.strip).count
            %small= "(#{number_to_percentage (motion.votes.officials.where(result: choice.strip).count.to_f/motion.votes.officials.count.to_f)*100, precision: 2})"
        %td= motion.votes.officials.count
        %td= motion.votes.officials.where("result IS NOT NULL").count
        %td= motion.votes.officials.where(result: nil).count

        - if @campaign.has_consultative_votes?
          - motion.choices.split(',').each do |choice|
            %td
              = motion.votes.consultatives.where(result: choice.strip).count
              %small= "(#{number_to_percentage (motion.votes.consultatives.where(result: choice.strip).count.to_f/motion.votes.consultatives.count.to_f)*100, precision: 2})"
          %td= motion.votes.consultatives.count
          %td= motion.votes.consultatives.where("result IS NOT NULL").count
          %td= motion.votes.consultatives.where(result: nil).count