config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  devise_for :users, controllers: {
    invitations: 'users/invitations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  get '/support', to: 'pages#support'
  get '/app', to: 'pages#app'
  get 'privacy', to: 'pages#privacy'

  get '/connexion', to: 'pages#connexion'
  get '/mot-de-passe-oublie', to: 'pages#forgot_password'

  resources :logos, only: :show
  resources :avatars, only: :show

  namespace :api, defaults: { format: 'json' } do
    get 'current_user', to: 'current_user#show'
    get 'switch/:id', to: 'current_user#switch', as: :switch_user
    get 'switch_back', to: 'current_user#switch_back', as: :switch_back
    post 'connect_with_google', to: 'sessions#connect_with_google', as: :connect_with_google
    post 'login', to: 'sessions#login', as: :login

    get '/:model/config', to: 'config#show'

    resources :users
    patch '/users/:id/enable', to: 'users#enable'
    patch '/users/:id/disable', to: 'users#disable'
    patch '/users/:id/add_role', to: 'users#add_role'
    patch '/users/:id/remove_role', to: 'users#remove_role'
    post '/users/:id/send_invitation', to: 'users#send_invitation'

    resources :churches
    post '/churches/:id/members', to: 'churches#add_members'
    delete '/churches/:id/members/:membership_id', to: 'churches#remove_members'
    post '/churches/:id/roles/edit', to: 'churches#edit_roles'

    resources :regions
    post '/regions/:id/members', to: 'regions#add_members'
    post '/regions/:id/roles/edit', to: 'regions#edit_roles'

    resources :associations
    post '/associations/:id/members', to: 'associations#add_members'
    post '/associations/:id/roles/edit', to: 'associations#edit_roles'

    resources :fees

    get '/notifications', to: 'notifications#index'
    patch '/notifications/:id/mark_as_read', to: 'notifications#mark_as_read'
    patch '/notifications/mark_all_as_read', to: 'notifications#mark_all_as_read'

    resources :device_tokens, only: [:create, :destroy]

    get '/profile', to: 'profile#show'

    get '/search', to: 'search#index'

    namespace :me do
      resources :events, only: [:index]
    end

    resources :memberships, only: [:update, :destroy]

    resources :campaigns
    patch '/campaigns/:id/change_state', to: 'campaigns#change_state'
    get '/campaigns/:id/voters_count', to: 'campaigns#voters_count'
    resources :events
    resources :posts
    resources :votes, only: [:index, :show, :create]
    resources :feed, only: [:index]

    resources :roles

    resources :files, only: [:destroy]
    resources :documents
    post '/update_order_documents', to: 'documents#update_order'
    resources :categories

    resources :push_notifications, only: [:index, :create, :update, :destroy]
    post '/push_notifications/send', to: 'push_notifications#send_notification'

    get 'referentiels/:referentiel', to: 'referentiels#show'
    get 'menus/:menu', to: 'menus#show'
  end

  # ADMIN SUBDOMAIN
  namespace :admin do
    resources :users, only: :index
    resources :churches, only: :index
    resources :associations, only: :index
    resources :campaigns, only: :index
    resources :events, only: :index
    resources :posts, only: :index
    resources :roles, only: :index
    resources :fees, only: :index
    resources :documents, only: :index
    resources :push_notifications, only: :index
    resources :regions, only: :index
    
    root to: redirect('/admin/users'), as: :root
  end

  # ASSOCIATION SUBDOMAIN
  namespace :association do
    resources :associations, only: :index
    resources :campaigns, only: :index

    root to: redirect('/association/associations'), as: :root
  end

  # REGION
  namespace :region do
    resources :members, only: :index
    resources :campaigns, only: :index
    resources :events, only: :index
    resources :posts, only: :index

    root to: redirect('/region/members'), as: :root
  end

  # ME SUBDOMAIN
  namespace :me, path: '' do
    get '/feed', to: 'feed#show', as: :feed
    get '/annuaire', to: 'annuaire#show', as: :annuaire
    get '/mon-profil', to: 'profile#show', as: :me
    get '/documents', to: 'documents#index', as: :documents
    get '/campaigns', to: 'campaigns#index', as: :votes
    get '/actus/:post', to: 'posts#show', as: :post
    get '/evenements/:event', to: 'events#show', as: :event

    root to: redirect('/feed'), as: :root
  end

  get '/campaigns/:id', to: 'campaigns#show'

  root to: redirect('/connexion')
end

app/views/layouts/_sidebar.html.haml
%ul.nav.navbar-nav

  %h3.menu-title Menu Principal
  %li{class: "#{(params[:controller] == 'pages') ? 'active' : ''}"}
    = link_to root_url do
      = icon 'fa', "home", class: "menu-icon"
      Accueil

  %li{class: "#{(params[:controller] == 'campaigns') ? 'active' : ''}"}
    = link_to campaigns_url do
      = icon 'fa', "comment", class: "menu-icon"
      Mes votes


  %li{class: "#{(params[:controller] == 'results') ? 'active' : ''}"}
    = link_to results_url do
      = icon 'fa', "comments", class: "menu-icon"
      Résultats

  / /.menu-title

  %h3.menu-title Mon compte
  / /.menu-title

  %li{class: "#{(params[:controller] == 'accounts') ? 'active' : ''}"}
    = link_to me_path do
      = icon 'fa', "user", class: "menu-icon"
      Consulter mon profil

  %li{class: "#{(params[:controller] == 'structures') ? 'active' : ''}"}
    = link_to structures_path do
      = icon 'fa', "address-book", class: "menu-icon"
      Consulter mes structures


  - if can? :manage, :all
    %h3.menu-title Administration
    %li{class: "#{(params[:controller] == 'admin/users') ? 'active' : ''}"}
      = link_to admin_users_url(subdomain: :admin) do
        = icon 'fa', "users", class: "menu-icon"
        Gestion des utilisateurs

    %li{class: "#{(params[:controller] == 'admin/campaigns') ? 'active' : ''}"}
      = link_to admin_campaigns_url(subdomain: :admin) do
        = icon 'fa', "comments", class: "menu-icon"
        Gestion des campagnes

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1.0"}
    %title Gestion des Votes FNADF/UNADF
    %meta{:name => "description", :content => "Application de votes electroniques de la FNADF"}

    = stylesheet_link_tag 'application', media: 'all'

    = favicon_link_tag "/favicon.ico"
    = csrf_meta_tags


    = javascript_include_tag 'application'

  %body
    / Left Panel
    %aside#left-panel.left-panel
      %nav.navbar.navbar-expand-sm.navbar-default
        .navbar-header
          %button.navbar-toggler{"aria-controls" => "main-menu", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#main-menu", "data-toggle" => "collapse", :type => "button"}
            %i.fa.fa-bars
          %a.navbar-brand{:href => "./"}
            FNADF / UNADF
          %a.navbar-brand.hidden{:href => "./"}
            FU

        #main-menu.main-menu.collapse.navbar-collapse
          = render "layouts/sidebar"
        / /.navbar-collapse
    / /#left-panel
    / Left Panel
    / Right Panel
    #right-panel.right-panel
      / Header
      %header#header.header
        .header-menu
          .col-md-12

            %a#menuToggle.menutoggle.float-left
              = icon 'fa', 'tasks'



            /= link_to "switch back", "/switch_user/remember_user"

            -  original_user = user_signed_in? && SwitchUser::Provider.init(controller).original_user
            - if original_user
              - next_path = ERB::Util.url_encode "/switch_user/remember_user?remember=false&path=/"
              = link_to "/switch_user?scope_identifier=user_#{original_user.id}&path=#{next_path}", class: 'btn btn-warning' do
                = icon 'fa', "back"
                Changer d'utilisateurs

            .user-area.dropdown.float-right
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#"}
                = current_user.name
              .user-menu.dropdown-menu
                = link_to me_path, class: 'nav-link' do
                  %i.fa.fa-.user>
                  Mon profil
                = link_to edit_me_path, class: 'nav-link' do
                  %i.fa.fa.-cog>
                  Modifier mon profil
                = link_to destroy_user_session_path, method: :delete, class: "nav-link" do
                  %i.fa.fa-power.-off>
                  Déconexion

      = yield

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
<head>
  <meta charset='utf-8' />
</head>
<body>
<div id="content">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/vuejs.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>
    <% if Rails.env == 'recette' %>
      RE7 - VOTES - INTRANET FNADF/UNADF
    <% elsif Rails.env == 'development' %>
      MYLOCAL - VOTES - INTRANET FNADF/UNADF
    <% else %>
      VOTES - INTRANET FNADF/UNADF
    <% end %>
  </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= vite_client_tag %>
</head>
<body>

<div id="app">
  <%= yield %>
</div>

<%= vite_javascript_tag 'application' %>

</body>
</html>